accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup')
]

aviaosite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('avioes/', include('avioes.urls')),
    path('admin/', admin.site.urls),
    
    path('accounts/', include('accounts.urls')), # linha adicionada para fazer a account
    path('accounts/', include('django.contrib.auth.urls')), # linha adicionada para fazer a account

]

avioes/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'avioes'
urlpatterns = [
    path('', views.AviaoListView.as_view(), name='index'),
    path('create/', views.AviaoCreateView.as_view(), name='create'),
    path('<int:pk>/', views.AviaoDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.AviaoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.AviaoDeleteView.as_view(), name='delete'),
    path('<int:aviao_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoriesListView.as_view(), name='categories'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category'),
    ]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

accounts/models.py
from django.db import models

# Create your models here.

avioes/models.py
from django.db import models
from django.conf import settings

# Create your models here.

# class Category(models.Model):
#     name = models.CharField(max_length=255)
#     # posts = models.ManyToManyField(Post)
#     description = models.CharField(max_length=255)
#     def __str__(self):
#         return f'{self.name}'

class Post(models.Model):
    name = models.CharField("Nome",max_length=255)
    caption = models.CharField("Legenda",max_length=255)
    poster_url = models.URLField("URL do avião",max_length=300, null=True)
    steps_url = models.URLField("URL das instruções",max_length=300, null=True)
    post_date = models.DateTimeField(auto_now_add=True)
    # category = models.ManyToManyField(Category)
    class Meta:
        ordering = ["-post_date"]
    
    def __str__(self):
        return f'{self.name} ({self.post_date})'
    

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    autor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    text = models.CharField("Comentário",max_length=255)
    post_date = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ["-post_date"]

    def __str__(self):
        return f'{self.autor}: {self.text} ({self.post_date})'

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post, blank = True)

    def __str__(self):
        return f'{self.name}'

avioes/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post, Comment, Category

class CreateAviaoForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

class UpdateAviaoForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'autor',
            'text',
        ]
        labels = {
            'autor': 'Usuário',
            'text': 'Comentário',
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'description')

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

avioes/views.py
from django.db.models import fields
from django.http import HttpResponseRedirect, request
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls.base import reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import Comment, Post, Category
from .forms import CreateAviaoForm, UpdateAviaoForm, CommentForm


class AviaoDetailView(generic.DetailView):
    model = Post
    template_name = 'avioes/detail.html'


class AviaoListView(generic.ListView):
    model = Post
    template_name = 'avioes/index.html'


class AviaoCreateView(generic.CreateView):
    model = Post
    fields = '__all__'
    template_name = 'avioes/create.html'
    def get_success_url(self):
        return reverse('avioes:detail', args=( self.object.id,))


class AviaoUpdateView(generic.UpdateView):
    model = Post
    fields = '__all__'
    template_name = 'avioes/update.html'
    def get_success_url(self):
        return reverse('avioes:detail', args=( self.object.id,))


class AviaoDeleteView(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('avioes:index')
    template_name = 'avioes/delete.html'



class CategoriesListView(generic.ListView):
    model = Category
    template_name = 'avioes/categories.html'


class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'avioes/category.html'

    
@login_required
def create_comment(request, aviao_id):
    aviao = get_object_or_404(Post, pk=aviao_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            # comment_author = form.cleaned_data['autor']
            comment_author = request.user
            comment_text = form.cleaned_data['text']
            comment = Comment(autor=comment_author,
                            text=comment_text,
                            post=aviao)
            comment.save()
            return HttpResponseRedirect(
                reverse('avioes:detail', args=(aviao_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'aviao': aviao}
    return render(request, 'avioes/comment.html', context)


def criar_aviao(request):
    if request.method == 'POST':
        # Obtém os dados do POST (sem validação)
        nome = request.POST.get('nome')
        descricao = request.POST.get('caption')

        # Cria um novo objeto Aviao (sem validação)
        aviao = aviao.objects.create(nome=nome, descricao=descricao)

        # Redireciona para a página de detalhes do novo avião
        return redirect('avioes:detail', aviao_id=aviao.id)
    else:
        return render(request, 'avioes/create.html')

staticpages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}
Criar Usuário
{% endblock title %}

{% block content %}
<h2>Criar Usuário</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %} 

avioes/templates/avioes/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <div class="lista-de-cards">
            <div class="card-categoria">
                <a href="{% url 'avioes:category' category.id %}"><header>{{category.name}}</header></a>
                <p>{{ category.description }}</p>
            </div>
        </div>
    </article>
    {% empty %}
    <p>Ainda não há categorias criadas.</p> 
    {% endfor %}



</section>

{% endblock content %}  

avioes/templates/avioes/category.html
{% extends 'base.html' %}
{% block title %}
Categoria {{category.name}}
{% endblock title %}
{% block content %}


<h2> Esses são todos os aviões da categoria {{category.name}} </h2>
<p>{{category.description}}</p>
{% if category %}
<section >
    {% for post in category.posts.all %}
    <article >
        <a href="{% url 'avioes:detail' post.id %}" > <p> {{ post.name}}</p></a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma aviao relacionado à categoria {{category.name}}.</p>
{% endif %}

{% endblock content %}

avioes/templates/avioes/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Adicionar comentário {{ aviao.name }}</h2>

<form action="{% url 'avioes:comment' aviao.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'avioes:detail' aviao.id %}">Voltar para a página do avião</a></p>
{% endblock content %}

avioes/templates/avioes/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Avião</h2>
<form method="POST" action="{% url 'avioes:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

avioes/templates/avioes/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'avioes:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o avião "{{ post.name }}" postado em {{ post.post_date|date:"D d M Y" }}?
    </p>
    <button id="delete" type="submit">Apagar</button>
</form>
<button id="cancelar"><a id="cancelar" href="{% url 'avioes:detail' post.id %}">Cancelar</a></button>
{% endblock content %}

avioes/templates/avioes/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} {{post.post_date}}
{% endblock title %}

{% block content %}
<h2>{{ post.name }}</h2>
<h3>{{post.caption}}</h3>
<h4>Postado em {{ post.post_date}}</h4>

<section class="detalhes">
    <img id="poster" src="{{ post.poster_url }}" alt="Poster do aviao {{ post.name}}">
    <h2>Instruções:</h2>
    <img id="steps" src="{{ post.steps_url }}" alt="Instruções para fazer um(a) {{ post.name}}">


    {% if post.category_set.all %}
    <h4 class="tags"> Incluso nas categorias:
    {% for category in post.category_set.all %}
        <li><a href="{% url 'avioes:category' category.id %}">{{ category.name }}</a></li>
    {% endfor %}</h4>
    {% endif %}
    
    <h4><a href="{% url 'avioes:update' pk=post.pk %}">Editar publicação</a></h4>
    <h4><a href="{% url 'avioes:delete' pk=post.pk %}">Deletar publicação</a></h4>

</section>


{% if post.id %}
<h2>
    Comentários
</h2>
    <h4><a href="{% url 'avioes:comment' post.pk %}">Adicionar comentário</a></h4>

    {% if post.comment_set.all %}
        {% for comment in post.comment_set.all %}
        <section class="comentario">
                <h4>{{comment.autor}}:</h4><h6></h6>
                <h4>{{comment.text}}</h4><h6> ({{comment.post_date|date:"D d M Y"}})</h6>
        </section>
        {% endfor %}
    {% else %}
    <p>Ainda não há nenhum comentário.</p>
    {% endif %}
{% endif %}

{% endblock content %}

avioes/templates/avioes/index.html
{% extends 'base.html' %}

{% block content %}
{% if categoria %}
<h2>Todos os Aviões da Categoria {{category}}</h2>
{% else %}
<h2>Todos os Aviões</h2>
{% endif %}
<section>
    <p>Quer contribuir para nosso acervo? <a href="{% url 'avioes:create' %}">Adicionar Novo avião</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'avioes:detail' post.id %}"><img src="{{ post.poster_url }}"
                alt="Poster do avião {{ post.name}}"></a>
        <p>{{ post.name }} ({{ post.post_date|date:"D d M Y" }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum avião.</p>
{% endif %}
{% endblock content %}

avioes/templates/avioes/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do avião "{{ object.name }}" (Postado em {{ object.post_date|date:"D d M Y"}})</h2>
<form method="POST" action="{% url 'avioes:update' object.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Esse site foi criado por Gabriel Morth Cursino para aplicar os conceitos aprendidos na disciplina PMR3304 - Sistemas de Informação.</h2>
<h3> Contato para mais dúvidas: gabrielmorth@usp.br</h3>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<p>Este é um site dedicado a trazer tutoriais de como fazer vários aviões de papel. Abaixo você encontra algumas curiosidades sobre eles.
    <ul>
        <li>A origem dos aviões de papel é normalmente atribuída à China Antiga, embora haja evidência de que foi concomitantemente aperfeiçoado e desenvolvido no Japão. Existem diversos modelos de aviões que possuem características diferentes.</li>
        <li>Você pode fazer o seu próprio avião de papel e competir com seus amigos!</li>
        <li> Várias instituições organizam suas próprias competições, como a RedBull.</li>
        <li>O recorde mundial de distância de voo foi quebrado e dezembro de 2022 pelo estadunidense Dillon Rubble, aluno de engenharia aeroespacial, que conseguiu jogar um avião de papel a 88 metros de distância! Confira o vídeo onde o Recorde mundial é quebrado: https://youtu.be/Cbh1cNA0W2A</li>
        <li>Vá em "Tutoriais" e tente fazer o seu avião de papel! Quem sabe você não entra para o Guiness Book também?</li>
    
    </ul>
     </p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img id="logo" src="{% static 'logonovo.png' %}"> </a>
        <h1>Aviões de Papel</h1>
        <nav id="navegacao-principal">
            <ul>
                {% if user.is_authenticated %}
                    <li> Logado com {{ user.username }} </li>
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Log in</a></li>
                {% endif %}
                
                <li><a href="{% url 'avioes:index' %}">Aviões</a></li>
                <li><a href="{% url 'avioes:categories' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023</small>
        </p>
    </footer>
</body>

</html>